### PR TITLE
Redefined css width property for service URI input element

### PR DESCRIPTION
**Pull request by tezvi**
Firefox 53+ does not support -moz-calc function anymore which results in too small width for html input element. Added calc function with same arguments and left -moz-calc for backwards compatibility with older Firefox versions.

### CODE REVIEW

**Comment by sabi0** [comment]
This is a duplicate of #256

**Comment by tezvi** [comment]
seems so, haven't seen it at the time of making this pull-request. The projects seems dead though :(

**Comment by sabi0** [comment]
You can add a workaround using Stylish. See #254.
It made RESTClient usable for me again.

**Comment by tezvi** [comment]
hey thx, just used Stylish and its usable again :)

**Comment by enriquezrene** [comment]
Hey

Please merge that PR

**Pull request closed without merging**
